# Generated by Django 5.2.4 on 2025-08-05 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obiekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polozenie_szerokosc', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('polozenie_dlugosc', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('obiekt', models.CharField(blank=True, max_length=100)),
                ('nazwa_geograficzna_polska', models.CharField(max_length=100)),
                ('nazwa_geograficzna_obca', models.CharField(blank=True, max_length=100)),
                ('wojewodztwo', models.CharField(blank=True, max_length=50)),
                ('powiat', models.CharField(max_length=50)),
                ('lokalizacja', models.CharField(blank=True, max_length=255)),
                ('typ_obiektu', models.CharField(max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('wysokosc', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('szerokosc', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('opis', models.TextField(blank=True, max_length=10000)),
                ('inskrypcja', models.TextField(blank=True, max_length=10000)),
                ('typ_pisma', models.CharField(blank=True, max_length=100)),
                ('tlumaczenie', models.TextField(blank=True, max_length=10000)),
                ('herby', models.TextField(blank=True, max_length=10000)),
                ('genealogia', models.TextField(blank=True, max_length=10000)),
                ('bibliografia', models.TextField(blank=True, max_length=10000)),
                ('odsylacze_do_zrodla', models.TextField(blank=True, max_length=10000)),
                ('autorzy_wpisu', models.CharField(blank=True, max_length=255)),
                ('data_wpisu', models.DateField(blank=True, null=True)),
                ('korekta_nr_1_autor', models.CharField(blank=True, max_length=255)),
                ('data_korekty_1', models.DateField(blank=True, null=True)),
                ('korekta_nr_2_autor', models.CharField(blank=True, max_length=255)),
                ('data_korekty_2', models.DateField(blank=True, null=True)),
                ('imie_nazwisko_osoby_upamietnionej', models.CharField(blank=True, max_length=255)),
                ('skan_3d', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Obiekt',
                'verbose_name_plural': 'Obiekty',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.ImageField(upload_to='zdjecia/%Y/%m/%d/')),
                ('obiekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecia', to='aplikacja.obiekt')),
            ],
        ),
    ]
