# Generated by Django 5.2.4 on 2025-08-27 19:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0002_alter_obiekt_polozenie_dlugosc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name': 'Zdjęcie', 'verbose_name_plural': 'Zdjęcia'},
        ),
        migrations.AddField(
            model_name='obiekt',
            name='data_powstania_obiektu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obiekt',
            name='status',
            field=models.CharField(choices=[('roboczy', 'Roboczy'), ('weryfikacja', 'Weryfikacja'), ('opublikowany', 'Opublikowany'), ('wycofany', 'Wycofany')], default='roboczy', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='obiekt',
            name='strona',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='obiekt',
            name='tom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obiekt',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Użytkownik który utworzył to zgłoszenie', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='plik',
            field=models.ImageField(upload_to='zdjecia/dodane'),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='autorzy_wpisu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='bibliografia',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='genealogia',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='herby',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='imie_nazwisko_osoby_upamietnionej',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='inskrypcja',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='korekta_nr_1_autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='korekta_nr_2_autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='lokalizacja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='nazwa_geograficzna_obca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='obiekt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='odsylacze_do_zrodla',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='opis',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='powiat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='skan_3d',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='tlumaczenie',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='typ_pisma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='wojewodztwo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
