# Generated by Django 5.2.4 on 2025-09-08 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_alter_foto_options_obiekt_data_powstania_obiektu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='obiekt',
            index=models.Index(fields=['wojewodztwo'], name='aplikacja_o_wojewod_3c8967_idx'),
        ),
        migrations.AddIndex(
            model_name='obiekt',
            index=models.Index(fields=['powiat'], name='aplikacja_o_powiat_9eac98_idx'),
        ),
        migrations.AddIndex(
            model_name='obiekt',
            index=models.Index(fields=['typ_obiektu'], name='aplikacja_o_typ_obi_574e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='obiekt',
            index=models.Index(fields=['lokalizacja'], name='aplikacja_o_lokaliz_180b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='obiekt',
            index=models.Index(fields=['status'], name='aplikacja_o_status_ba419e_idx'),
        ),
        migrations.AddIndex(
            model_name='obiekt',
            index=models.Index(fields=['nazwa_geograficzna_polska'], name='aplikacja_o_nazwa_g_af29a3_idx'),
        ),
    ]
