# Generated by Django 5.2.4 on 2025-09-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0004_obiekt_aplikacja_o_wojewod_3c8967_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='plik_oryginalny',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia/oryginalne'),
        ),
    ]
