# Generated by Django 5.2.4 on 2025-11-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0005_foto_plik_oryginalny'),
    ]

    operations = [
        migrations.AddField(
            model_name='obiekt',
            name='uwagi',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
